--script exportado do H2 para criar no MySql (usando Heidi)

CREATE TABLE `CLIENTE`(
    `ID` INTEGER NOT NULL,
    `CPF` VARCHAR(5),
    `NOME` VARCHAR(255)
);
ALTER TABLE `CLIENTE` ADD CONSTRAINT `CONSTRAINT_5` PRIMARY KEY(`ID`);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLIENTE;
CREATE TABLE `ITEM_PEDIDO`(
    `ID` INTEGER NOT NULL,
    `QUANTIDADE` INTEGER,
    `PEDIDO_ID` INTEGER,
    `PRODUTO_ID` INTEGER
);
ALTER TABLE `ITEM_PEDIDO` ADD CONSTRAINT `CONSTRAINT_5C` PRIMARY KEY(`ID`);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM_PEDIDO;
CREATE TABLE `PEDIDO`(
    `ID` INTEGER NOT NULL,
    `DATA_PEDIDO` DATE,
    `TOTAL` DECIMAL(19, 2),
    `CLIENTE_ID` INTEGER
);
ALTER TABLE `PEDIDO` ADD CONSTRAINT `CONSTRAINT_8` PRIMARY KEY(`ID`);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PEDIDO;
CREATE TABLE `PRODUTO`(
    `ID` INTEGER NOT NULL,
    `DESCRICAO` VARCHAR(255),
    `PRECO_UNITARIO` DECIMAL(19, 2)
);
ALTER TABLE `PRODUTO` ADD CONSTRAINT `CONSTRAINT_1` PRIMARY KEY(`ID`);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUTO;
ALTER TABLE `ITEM_PEDIDO` ADD CONSTRAINT `FKTK55MN6D6BVL5H0NO5UAGI3SF` FOREIGN KEY(`PRODUTO_ID`) REFERENCES `PRODUTO`(`ID`);
ALTER TABLE `PEDIDO` ADD CONSTRAINT `FK30S8J2KTPAY6OF18LBYQN3632` FOREIGN KEY(`CLIENTE_ID`) REFERENCES `CLIENTE`(`ID`);
ALTER TABLE `ITEM_PEDIDO` ADD CONSTRAINT `FK60YM08CFOYSA17WRN1SWYIUDA` FOREIGN KEY(`PEDIDO_ID`) REFERENCES `PEDIDO`(`ID`);